/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-12-28 14:07:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class _01_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP '01.jsp' starting page</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/common.css\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-1.11.1.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\".thumbs a\").click(function(){\r\n");
      out.write("\t\t\t\tvar largePath  = $(this).attr(\"href\");\r\n");
      out.write("\t\t\t\tvar largeAlt = $(this).attr(\"title\");\r\n");
      out.write("\t\t\t\t$(\"#largeImg\").attr({\r\n");
      out.write("\t\t\t\t\tsrc : largePath,\r\n");
      out.write("\t\t\t\t\talt : largeAlt\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#myfile\").change(function(){\r\n");
      out.write("\t\t\t\t$(\"#previewImg\").attr(\"src\",\"file:///\" + $(\"#myfile\").val());\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar la = $(\"#large\");\r\n");
      out.write("\t\t\tla.hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#previewImg\").mousemove(function(e){\r\n");
      out.write("\t\t\t\tla.css({\r\n");
      out.write("\t\t\t\t\ttop : e.pageY,\r\n");
      out.write("\t\t\t\t\tleft : e.pageX\r\n");
      out.write("\t\t\t\t}).html('<img src = \"' + this.src + '\" />').show();\r\n");
      out.write("\t\t\t}).mouseout(function(){\r\n");
      out.write("\t\t\t\tla.hide();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t\t/*  //使用js实现文件上传图片的预览\r\n");
      out.write("\t\tfunction showPreview(obj){\r\n");
      out.write("\t\t\tvar str = obj.value;\r\n");
      out.write("\t\t\tdocument.getElementById(\"previewImg\").innerHTML = \r\n");
      out.write("\t\t\t\t\"<img src = '\" + str + \"' />\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t*/\r\n");
      out.write("\t</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("  \t <img id=\"previewImg\" src=\"images/preview.jpg\" width=\"80\" height=\"80\" />\r\n");
      out.write("  \t <br><br>\r\n");
      out.write("  \t <form action=\"uploadServlet.do\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("  \t\t请选择图片：<input id=\"myfile\" name=\"myfile\" type=\"file\" onchange=\"showPreview(this)\"/>\r\n");
      out.write("  \t\t<input type=\"submit\" value=\"提交\"  />");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("  \t</form>\r\n");
      out.write("  \t\r\n");
      out.write("  \t下载：<a href=\"downloadServlet.do?filename=a.txt\">a.txt</a> &nbsp;&nbsp; ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorResult}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div id=\"large\"></div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<hr>\r\n");
      out.write("    <h2>图片预览</h2>\r\n");
      out.write("    <p><img id=\"largeImg\" src=\"images/img1-lg.jpg\" alt=\"Large Image\"/></p>\r\n");
      out.write("    <p class=\"thumbs\">\r\n");
      out.write("    \t<a href=\"images/img2-lg.jpg\" title=\"Image2\"><img src=\"images/img2-thumb.jpg\"></a>\r\n");
      out.write("    \t<a href=\"images/img3-lg.jpg\" title=\"Image3\"><img src=\"images/img3-thumb.jpg\"></a>\r\n");
      out.write("    \t<a href=\"images/img4-lg.jpg\" title=\"Image4\"><img src=\"images/img4-thumb.jpg\"></a>\r\n");
      out.write("    \t<a href=\"images/img5-lg.jpg\" title=\"Image5\"><img src=\"images/img5-thumb.jpg\"></a>\r\n");
      out.write("    \t<a href=\"images/img6-lg.jpg\" title=\"Image6\"><img src=\"images/img6-thumb.jpg\"></a>\r\n");
      out.write("    </p>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
