/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-12-27 03:52:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class UsersLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!-- 这是一个html5 doctype声明 -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>用户登录</title>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write("\tmargin:0px;\r\n");
      out.write("\tpadding:0px;\r\n");
      out.write("\toverflow:hidden;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#wrapper{\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:100%;\r\n");
      out.write("\tmin-width:1280px;\r\n");
      out.write("\tmin-height:680px;\r\n");
      out.write("\toverflow-x:hidden;\r\n");
      out.write("\toverflow-y:hidden;\r\n");
      out.write(" background-image: -moz-linear-gradient(top,#77D1F6, #2F368F);\r\n");
      out.write("    background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, #77D1F6),color-stop(1, #2F368F)); \r\n");
      out.write("}\r\n");
      out.write("#header{\r\n");
      out.write("\theight:100px;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("}\r\n");
      out.write("#logo{\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tmargin-left:5%;\r\n");
      out.write("\tmargin-top:30px;\r\n");
      out.write("\theight:40px;\r\n");
      out.write("\twidth:160px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("#heading{\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tmargin-left:20%;\r\n");
      out.write("\tmargin-top:-18px;\r\n");
      out.write("\theight:110px;\r\n");
      out.write("\twidth:60%;\r\n");
      out.write("\tborder-radius: 18px;\r\n");
      out.write("\tbackground-color:#1C75BC;\r\n");
      out.write("\topacity:0.6;\r\n");
      out.write("}\r\n");
      out.write("#heading #title{\r\n");
      out.write("\tmargin-top:30px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tfont-family:微软雅黑;\r\n");
      out.write("\tfont-size:39px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tcolor:#DC143C;\r\n");
      out.write("}\r\n");
      out.write("#heading #subTitle{\r\n");
      out.write("\tmargin-top:10px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tfont-family:Courier New;\r\n");
      out.write("\tfont-size:10px;\r\n");
      out.write("}\r\n");
      out.write("#main{\r\n");
      out.write("\tmargin-top:20px;\r\n");
      out.write("\theight:500px;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("}\r\n");
      out.write("#mainBg{\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tmargin-left:20%;\r\n");
      out.write("\tmargin-top:0px;\r\n");
      out.write("\theight:500px;\r\n");
      out.write("\twidth:60%;\r\n");
      out.write("    border-radius: 18px;\r\n");
      out.write("    background-color:#000000;\r\n");
      out.write("    opacity:0.5;\r\n");
      out.write("}\r\n");
      out.write("#mainPanel{\r\n");
      out.write("    position:relative;\r\n");
      out.write("\tmargin:25px;\r\n");
      out.write("\theight:450px;\r\n");
      out.write("    border-radius: 18px;\r\n");
      out.write("    background-image: -moz-linear-gradient(top,#EBEBEB, #BFBFBF);\r\n");
      out.write("    background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, #EBEBEB),color-stop(1, #BFBFBF));\r\n");
      out.write("}\r\n");
      out.write("#mainPanel #left{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tborder-right:2px solid #F6F6F6;\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\ttop:10%;\r\n");
      out.write("\theight:80%;\r\n");
      out.write("\twidth:49%;\r\n");
      out.write("\tborder-right-style:groove;\r\n");
      out.write("}\r\n");
      out.write("#mainPanel #image{\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\theight:256px;\r\n");
      out.write("\twidth:256px;\r\n");
      out.write("\tleft:15%;\r\n");
      out.write("\ttop:12%;\r\n");
      out.write("\tbackground-image:url('../images/admin.png');\r\n");
      out.write("}\r\n");
      out.write("#mainPanel #right{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\theight:90%;\r\n");
      out.write("\twidth:49%;\r\n");
      out.write("\ttop:5%;\r\n");
      out.write("}\r\n");
      out.write("#welcome{\r\n");
      out.write("\tmargin-top:20px;\r\n");
      out.write("\theight:60px;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tline-height: 60px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("#welcome #welcome-text{\r\n");
      out.write("\tfont-size:38px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tfont-family:微软雅黑;\r\n");
      out.write("\ttext-shadow: 0 1px 1px #F6F6F6;\r\n");
      out.write("}\r\n");
      out.write("#user-name{\r\n");
      out.write("\theight:35px;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tmargin-top:20px;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tline-height: 35px;\r\n");
      out.write("}\r\n");
      out.write("#user-password{\r\n");
      out.write("\tmargin-top:20px;\r\n");
      out.write("\theight:35px;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tline-height: 35px;\r\n");
      out.write("}\r\n");
      out.write("#user-checkcode{\r\n");
      out.write("\tmargin-top:20px;\r\n");
      out.write("\theight:35px;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tline-height: 35px;\r\n");
      out.write("}\r\n");
      out.write("#button-group{\r\n");
      out.write("\tmargin-top:10px;\r\n");
      out.write("\theight:35px;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tline-height: 35px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("#error-tip{\r\n");
      out.write("\tmargin-top:20px;\r\n");
      out.write("\tmargin-left:5%;\r\n");
      out.write("\theight:40px;\r\n");
      out.write("\twidth:90%;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tline-height: 35px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tborder-bottom:2px solid #F6F6F6;\r\n");
      out.write("\tborder-bottom-style:groove;\r\n");
      out.write("}\r\n");
      out.write("#error-tip #tip-text{\r\n");
      out.write("\tfont-size:18px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tfont-family:微软雅黑;\r\n");
      out.write("\tcolor:red;\r\n");
      out.write("}\r\n");
      out.write(".item{\r\n");
      out.write("\tmargin-left:20px;\r\n");
      out.write("\tfont-family:微软雅黑;\r\n");
      out.write("\tfont-size:20px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth:80px;\r\n");
      out.write("\tmargin-top: 3px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttext-shadow: 0 1px 1px #F6F6F6;\r\n");
      out.write("}\r\n");
      out.write(".input{\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("#checkcode-img{\r\n");
      out.write("\tmargin-top:3px;\r\n");
      out.write("\theight:20px;\r\n");
      out.write("\twidth:60px;\r\n");
      out.write("}\r\n");
      out.write(".form-input{\r\n");
      out.write("\theight:20px;\r\n");
      out.write("}\r\n");
      out.write(".btn{\r\n");
      out.write("    border:1px solid #cccccc;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("    margin:10px 5px;\r\n");
      out.write("    height:40px;\r\n");
      out.write("\twidth:80px;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    border-color: #636263 #464647 #A1A3A5;\r\n");
      out.write("    text-shadow: 0 1px 1px #F6F6F6;\r\n");
      out.write("    background-image: -moz-linear-gradient(center top, #D9D9D9, #A6A6A6 49%, #A6A6A6 50%);\r\n");
      out.write("    background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, #D9D9D9),color-stop(1, #A6A6A6));\r\n");
      out.write("}\r\n");
      out.write("#footer{\r\n");
      out.write("\tmargin-top:20px;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("}\r\n");
      out.write("#footer #text{\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tfont-size:14px;\r\n");
      out.write("\tfont-family:微软雅黑;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- <div> 可定义文档中的分区或节（division/section）\r\n");
      out.write("<div> 标签可以把文档分割为独立的、不同的部分。它可以用作严格的组织工具，并且不使用任何格式与其关联。\r\n");
      out.write(" -->\r\n");
      out.write(" <div id=\"wrapper\">\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<div id=\"logo\"></div>\r\n");
      out.write("\t\t<div id=\"heading\">\r\n");
      out.write("\t\t\t<div id=\"title\">欢&nbsp;乐&nbsp;校&nbsp;园&nbsp;购</div>\r\n");
      out.write("\t\t\t<div id=\"subTitle\">最新版</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\t\t<div id=\"mainBg\">\r\n");
      out.write("\t\t\t<div id=\"mainPanel\">\r\n");
      out.write("\t\t\t\t<div id=\"left\">\r\n");
      out.write("\t\t\t\t\t<div id=\"image\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"right\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<form name=\"loginForm\" action=\"");
      out.print(path);
      out.write("/users/Users_login.action\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<!-- start of login form -->\r\n");
      out.write("\t\t\t\t\t<div id=\"welcome\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"welcome-text\">欢&nbsp;迎&nbsp;登&nbsp;录</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"user-name\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"item\">用户名:</span>\r\n");
      out.write("\t\t\t\t\t\t<span><input type=\"text\" name=\"username\" class=\"form-input\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"user-password\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"item\">密&nbsp;&nbsp;&nbsp;码:</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"input\"><input type=\"password\" name=\"password\" class=\"form-input\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t <div id=\"button-group\">\r\n");
      out.write("\t\t\t\t\t <input type=\"radio\" name=\"identity\" value=\"用户\" class=\"btn\" checked=\"checked\"/>\r\n");
      out.write("\t\t\t\t\t <font size=\"5\"><b>用户</b></font>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("                     <input type=\"radio\" name=\"identity\" value=\"管理员\" class=\"btn\"/>\r\n");
      out.write("                     <font size=\"5\"><b>管理员</b>\r\n");
      out.write("\t\t\t\t </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t<div id=\"button-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" class=\"btn\" value=\"登录\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"reset\" class=\"btn\" value=\"重置\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t  ");
      if (_jspx_meth_s_005ffielderror_005f0(_jspx_page_context))
        return;
      out.write(" <!-- 显示表单验证的出错信息 -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- end of form -->\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t\t<div id=\"text\">Copyright © 2009-2015 All Rights Reserved Powered By Simoniu</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005ffielderror_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:fielderror
    org.apache.struts2.views.jsp.ui.FieldErrorTag _jspx_th_s_005ffielderror_005f0 = (org.apache.struts2.views.jsp.ui.FieldErrorTag) _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.get(org.apache.struts2.views.jsp.ui.FieldErrorTag.class);
    _jspx_th_s_005ffielderror_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005ffielderror_005f0.setParent(null);
    int _jspx_eval_s_005ffielderror_005f0 = _jspx_th_s_005ffielderror_005f0.doStartTag();
    if (_jspx_th_s_005ffielderror_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.reuse(_jspx_th_s_005ffielderror_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ffielderror_005fnobody.reuse(_jspx_th_s_005ffielderror_005f0);
    return false;
  }
}
