/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-12-27 10:58:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class buyerCenter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>买家中心</title>\r\n");
      out.write("\t<meta http-equiv=\"content-type\" content=\"text/html;charset=UTF-8\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../../css/index.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<div id=\"logo\"><b>欢乐校园购</b></div>\r\n");
      out.write("\t\t<div id=\"title\">买家中心</div>\r\n");
      out.write("\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t<div id=\"menu_container\">\r\n");
      out.write("\t\t\t\t<ul id=\"menu_items\">\r\n");
      out.write("\t\t\t\t    <li class=\"menu_item\" onmouseout=\"this.style.backgroundColor='';this.style.fontWeight='normal'\" onmouseover=\"this.style.backgroundColor='#77D1F6';this.style.fontWeight='bold'\"><a href=\"");
      out.print(path);
      out.write("/users/Users_logout.action\">首页</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"menu_item on\" style=\"border-radius:8px 0 0 8px\" onmouseout=\"this.style.backgroundColor=''\" onmouseover=\"this.style.backgroundColor='#77D1F6';this.style.borderRadius='8px 0 0 8px'\"><a href=\"");
      out.print(path);
      out.write("/users/Users_logout.action\">我的订单</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"menu_item\" onmouseout=\"this.style.backgroundColor='';this.style.fontWeight='normal'\" onmouseover=\"this.style.backgroundColor='#77D1F6';this.style.fontWeight='bold'\"><a href=\"");
      out.print(path);
      out.write("/users/Users_logout.action\">我的购物车</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"menu_item\" onmouseout=\"this.style.backgroundColor='';this.style.fontWeight='normal'\" onmouseover=\"this.style.backgroundColor='#77D1F6';this.style.fontWeight='bold'\"><a href=\"");
      out.print(path);
      out.write("/users/Users_logout.action\">我的消息</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"menu_item\" onmouseout=\"this.style.backgroundColor='';this.style.fontWeight='normal'\" onmouseover=\"this.style.backgroundColor='#77D1F6';this.style.fontWeight='bold'\"><a>相册管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"menu_item\" style=\"border-radius:8px 0 0 8px;border:0px;\" onmouseout=\"this.style.backgroundColor='';this.style.fontWeight='normal'\" onmouseover=\"this.style.backgroundColor='#77D1F6';this.style.borderRadius='0 8px 8px 0';this.style.fontWeight='bold'\"><a>邮件管理</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"user_info\">\r\n");
      out.write("\t\t\t<div id=\"welcome\">欢迎");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("使用本系统</div>\r\n");
      out.write("\t\t\t<div id=\"logout\"><a href=\"");
      out.print(path);
      out.write("/users/Users_logout.action\">安全退出</a></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"navigator\">\r\n");
      out.write("\t\t<iframe src=\"../../buyerCenterTree.jsp\"></iframe>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\t\t<iframe name=\"MainFrame\" src=\"UsersOutputInformation.jsp\"></iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"footer\">Copyright © 2009-2015 All Rights Reserved Powered By Somoniu</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function screenAdapter(){\r\n");
      out.write("\tdocument.getElementById('footer').style.top=document.documentElement.scrollTop+document.documentElement.clientHeight- document.getElementById('footer').offsetHeight+\"px\";\r\n");
      out.write("\t\tdocument.getElementById('navigator').style.height=document.documentElement.clientHeight-100+\"px\";\r\n");
      out.write("\t\tdocument.getElementById('main').style.height=document.documentElement.clientHeight-100+\"px\";\r\n");
      out.write("\t\tdocument.getElementById('main').style.width=window.screen.width-230+\"px\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("window.onscroll=function(){screenAdapter();};\r\n");
      out.write("window.onresize=function(){screenAdapter();};\r\n");
      out.write("window.onload=function(){screenAdapter();};\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
