/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-12-27 06:46:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class UsersOutputInformation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<meta http-equiv=\"content-type\" content=\"text/html;charset=UTF-8\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../../css/default.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("    background: none repeat scroll 0 0 transparent;\r\n");
      out.write("    border: 0 none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    vertical-align: baseline;\r\n");
      out.write("\tfont-family:微软雅黑;\r\n");
      out.write("\toverflow:hidden;\r\n");
      out.write("}\r\n");
      out.write("#navi{\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tword-wrap:break-word;\r\n");
      out.write("\tborder-bottom:1px solid #065FB9;\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tpadding:0;\r\n");
      out.write("\theight:40px;\r\n");
      out.write("\tline-height:40px;\r\n");
      out.write("\tvertical-align:middle;\r\n");
      out.write("    background-image: -moz-linear-gradient(top,#EBEBEB, #BFBFBF);\r\n");
      out.write("    background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, #EBEBEB),color-stop(1, \r\n");
      out.write("#BFBFBF));\r\n");
      out.write("}\r\n");
      out.write("#naviDiv{\r\n");
      out.write("\tfont-size:14px;\r\n");
      out.write("\tcolor:#333;\r\n");
      out.write("\tpadding-left:10px;\r\n");
      out.write("}\r\n");
      out.write("#tips{\r\n");
      out.write("\tmargin-top:10px;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:40px;\r\n");
      out.write("}\r\n");
      out.write("#buttonGroup{\r\n");
      out.write("\tpadding-left:10px;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\theight:35px;\r\n");
      out.write("}\r\n");
      out.write(".button{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tmargin-right:10px;\r\n");
      out.write("\tpadding-left:10px;\r\n");
      out.write("\tpadding-right:10px;\r\n");
      out.write("\tfont-size:14px;\r\n");
      out.write("\twidth:70px;\r\n");
      out.write("\theight:30px;\r\n");
      out.write("\tline-height:30px;\r\n");
      out.write("\tvertical-align:middle;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("    border-color: #77D1F6;\r\n");
      out.write("    border-width: 1px;\r\n");
      out.write("    border-style: solid;\r\n");
      out.write("    border-radius: 6px 6px;\r\n");
      out.write("    -moz-box-shadow: 2px 2px 4px #282828;\r\n");
      out.write("    -webkit-box-shadow: 2px 2px 4px #282828;\r\n");
      out.write("    background-image: -moz-linear-gradient(top,#EBEBEB, #BFBFBF);\r\n");
      out.write("    background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, #EBEBEB),color-stop(1, #BFBFBF));\r\n");
      out.write("}\r\n");
      out.write("#mainContainer{\r\n");
      out.write("\tpadding-left:10px;\r\n");
      out.write("\tpadding-right:10px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\twidth:98%;\r\n");
      out.write("\tfont-size:12px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"navi\">\r\n");
      out.write("\t<!-- 导航空白 -->\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"tips\">\r\n");
      out.write("\t<!-- 导航空白 -->\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"mainContainer\">\r\n");
      out.write("   <img src=\"../../images/welcome.jpg\">\r\n");
      out.write("   <!--数据表格空白 -->\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
